import { useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { getBreed } from '../lib/companion-breeds';
import { getAccessory } from '../lib/companion-accessories';

// CompanionCat — cinematic animated cat renderer.
//
// Render paths (in priority order):
// 1. PNG portrait — if /companion/breeds/{breed}.png exists (generated by
//    `npm run gen:cats`). Accessory PNGs composited on top as <img> overlays.
// 2. SVG fallback — full-anatomy vector cat with SVG filter-based fur texture,
//    subsurface scattering simulation, rim lighting, and rich animation.
//
// Props:
//   cat   — the cat object from companion-store
//   mood  — 'healthy' | 'concerned' | 'distressed' | 'critical' | 'glowing'
//   size  — pixel canvas size (default 380)

const breedImageCache = new Map();
const accImageCache = new Map();

function probeImage(src) {
  const cached = breedImageCache.get(src);
  if (cached) return cached;
  const p = new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(img.naturalWidth > 0);
    img.onerror = () => resolve(false);
    img.src = src;
  });
  breedImageCache.set(src, p);
  return p;
}

function probeAccImage(key) {
  if (accImageCache.has(key)) return accImageCache.get(key);
  const p = probeImage(`/companion/accessories/${key}.png`);
  accImageCache.set(key, p);
  return p;
}

export default function CompanionCat({ cat, mood = 'healthy', size = 380 }) {
  if (!cat) return null;
  const breed = getBreed(cat.breed);
  const palette = breed.palette;
  const sizeMult = cat.appearance?.sizeMultiplier ?? 1;
  const fur = cat.appearance?.furQuality || 'normal';
  const equipped = cat.appearance?.equippedAccessories || [];

  const [hasImage, setHasImage] = useState(false);
  const [accImages, setAccImages] = useState({});

  useEffect(() => {
    let alive = true;
    probeImage(`/companion/breeds/${cat.breed}.png`).then((ok) => alive && setHasImage(ok));
    return () => { alive = false; };
  }, [cat.breed]);

  useEffect(() => {
    let alive = true;
    Promise.all(
      equipped.map((key) => probeAccImage(key).then((ok) => [key, ok]))
    ).then((results) => {
      if (!alive) return;
      const m = {};
      results.forEach(([k, ok]) => { m[k] = ok; });
      setAccImages(m);
    });
    return () => { alive = false; };
  }, [equipped.join(',')]); // eslint-disable-line react-hooks/exhaustive-deps

  const isGlowing = mood === 'glowing' || fur === 'glowing';
  const isCritical = mood === 'critical';

  return (
    <motion.div
      animate={{
        scale: sizeMult,
        y: isCritical ? 0 : [0, -4, 0],
        x: mood === 'distressed' ? [-1.5, 1.5, -1, 1, 0] : 0,
      }}
      transition={{
        scale: { type: 'spring', stiffness: 90, damping: 14 },
        y: { duration: 4.8, repeat: Infinity, ease: 'easeInOut' },
        x: mood === 'distressed'
          ? { duration: 0.35, repeat: Infinity, repeatType: 'mirror' }
          : { duration: 0 },
      }}
      style={{
        width: size,
        height: size,
        display: 'flex',
        alignItems: 'flex-end',
        justifyContent: 'center',
        filter: isGlowing
          ? `drop-shadow(0 0 32px ${palette.eyes}cc) drop-shadow(0 0 70px ${palette.eyes}66) drop-shadow(0 14px 28px rgba(0,0,0,0.55))`
          : 'drop-shadow(0 14px 32px rgba(0,0,0,0.6))',
      }}
    >
      {hasImage ? (
        <PngCat cat={cat} breed={breed} mood={mood} equipped={equipped} accImages={accImages} size={size} />
      ) : (
        <CatSvg cat={cat} breed={breed} mood={mood} equipped={equipped} accImages={accImages} />
      )}
    </motion.div>
  );
}

// ─── PNG portrait wrapper ──────────────────────────────────────────────────

function PngCat({ cat, breed, mood, equipped, accImages, size }) {
  return (
    <div style={{ position: 'relative', width: '100%', height: '100%' }}>
      <img
        src={`/companion/breeds/${cat.breed}.png`}
        alt={breed.label}
        style={{ width: '100%', height: '100%', objectFit: 'contain' }}
        draggable={false}
      />
      {equipped.map((key) => {
        const acc = getAccessory(key);
        if (!acc?.render || !accImages[key]) return null;
        const { cx, cy, w, h, rotation } = acc.render;
        // Map SVG viewBox (280x280) coords to percentage of container
        return (
          <img
            key={key}
            src={`/companion/accessories/${key}.png`}
            alt={acc.label}
            draggable={false}
            style={{
              position: 'absolute',
              left: `${((cx - w / 2) / 280) * 100}%`,
              top: `${((cy - h / 2) / 280) * 100}%`,
              width: `${(w / 280) * 100}%`,
              height: `${(h / 280) * 100}%`,
              objectFit: 'contain',
              transform: `rotate(${rotation}deg)`,
              transformOrigin: 'center center',
              pointerEvents: 'none',
            }}
          />
        );
      })}
    </div>
  );
}

// ─── SVG cat renderer ─────────────────────────────────────────────────────

function CatSvg({ cat, breed, mood, equipped, accImages }) {
  const { palette, silhouette } = breed;
  const id = (cat.id || 'cat').replace(/[^a-z0-9]/gi, '').slice(0, 12) || 'cat';

  const eyeOpen = mood === 'critical' ? 0.1 : mood === 'distressed' ? 0.6 : mood === 'concerned' ? 0.88 : 1;
  const isCritical = mood === 'critical';
  const earTilt = mood === 'concerned' ? -10 : mood === 'distressed' ? -18 : isCritical ? -24 : 0;
  const isGlowing = mood === 'glowing';

  const bodyW = silhouette.body === 'plush' ? 78 : silhouette.body === 'sleek' ? 60 : 70;
  const bodyH = silhouette.body === 'plush' ? 52 : silhouette.body === 'sleek' ? 42 : 48;

  return (
    <svg
      viewBox="0 0 280 280"
      width="100%"
      height="100%"
      xmlns="http://www.w3.org/2000/svg"
      style={{ overflow: 'visible' }}
    >
      <defs>
        {/* ── Colour gradients ── */}
        <radialGradient id={`body-${id}`} cx="42%" cy="30%" r="72%">
          <stop offset="0%"   stopColor={lighten(palette.body, 0.38)} />
          <stop offset="40%"  stopColor={lighten(palette.body, 0.12)} />
          <stop offset="72%"  stopColor={palette.body} />
          <stop offset="100%" stopColor={darken(palette.body, 0.35)} />
        </radialGradient>
        <radialGradient id={`head-${id}`} cx="40%" cy="30%" r="80%">
          <stop offset="0%"   stopColor={lighten(palette.body, 0.42)} />
          <stop offset="38%"  stopColor={lighten(palette.body, 0.16)} />
          <stop offset="68%"  stopColor={palette.body} />
          <stop offset="100%" stopColor={darken(palette.body, 0.38)} />
        </radialGradient>
        <linearGradient id={`eye-${id}`} x1="20%" y1="0%" x2="80%" y2="100%">
          <stop offset="0%"   stopColor={lighten(palette.eyes, 0.55)} />
          <stop offset="40%"  stopColor={palette.eyes} />
          <stop offset="100%" stopColor={darken(palette.eyes, 0.55)} />
        </linearGradient>
        <radialGradient id={`pink-${id}`} cx="40%" cy="35%">
          <stop offset="0%"   stopColor="#ffcece" />
          <stop offset="70%"  stopColor="#e89898" />
          <stop offset="100%" stopColor="#c87070" />
        </radialGradient>
        <radialGradient id={`belly-${id}`} cx="50%" cy="40%" r="60%">
          <stop offset="0%"   stopColor={lighten(palette.belly, 0.18)} />
          <stop offset="100%" stopColor={palette.belly} />
        </radialGradient>
        <radialGradient id={`nose-${id}`} cx="40%" cy="35%">
          <stop offset="0%"   stopColor={lighten(palette.nose, 0.3)} />
          <stop offset="100%" stopColor={palette.nose} />
        </radialGradient>

        {/* ── Pattern fills ── */}
        {silhouette.pattern === 'stripes' && (
          <pattern id={`pat-${id}`} x="0" y="0" width="18" height="18" patternUnits="userSpaceOnUse">
            <rect width="18" height="18" fill="transparent" />
            <path d="M-2 9 Q 9 3 20 9" stroke={darken(palette.body, 0.45)} strokeWidth="3.5" fill="none" opacity="0.65" />
          </pattern>
        )}
        {silhouette.pattern === 'spots' && (
          <pattern id={`pat-${id}`} x="0" y="0" width="22" height="22" patternUnits="userSpaceOnUse">
            <rect width="22" height="22" fill="transparent" />
            <ellipse cx="7" cy="8" rx="3.2" ry="2.4" fill={darken(palette.body, 0.48)} opacity="0.7" />
            <ellipse cx="16" cy="15" rx="2.2" ry="1.6" fill={darken(palette.body, 0.48)} opacity="0.6" />
          </pattern>
        )}

        {/* ── SVG Filters ── */}

        {/* Fur texture displacement — organic surface distortion */}
        <filter id={`fur-${id}`} x="-5%" y="-5%" width="110%" height="110%">
          <feTurbulence type="fractalNoise" baseFrequency="0.045 0.055" numOctaves="4" seed={id.charCodeAt(0) % 20 + 1} result="noise" />
          <feDisplacementMap in="SourceGraphic" in2="noise" scale="9" xChannelSelector="R" yChannelSelector="G" result="displaced" />
          <feGaussianBlur in="displaced" stdDeviation="0.4" />
        </filter>

        {/* Subsurface scatter — warm backlight through ears */}
        <filter id={`sss-${id}`} x="-20%" y="-20%" width="140%" height="140%">
          <feGaussianBlur stdDeviation="9" result="blur" />
          <feColorMatrix in="blur" type="matrix"
            values="2.5 0.4 0.1 0 0.05
                    0.8 1.2 0.1 0 0
                    0   0   0.4 0 0
                    0   0   0   0.55 0"
            result="warmed" />
          <feComposite in="warmed" in2="SourceGraphic" operator="in" />
        </filter>

        {/* Rim light — cool blue-white edge along upper-right */}
        <filter id={`rim-${id}`} x="-10%" y="-10%" width="120%" height="120%">
          <feMorphology operator="dilate" radius="3.5" result="expanded" />
          <feComposite in="expanded" in2="SourceGraphic" operator="out" result="rimShape" />
          <feFlood floodColor="#c8dff8" floodOpacity="0.55" result="rimColor" />
          <feComposite in="rimColor" in2="rimShape" operator="in" />
        </filter>

        {/* Glowing mood — pulsing soft halo */}
        <filter id={`glow-${id}`} x="-30%" y="-30%" width="160%" height="160%">
          <feGaussianBlur stdDeviation="20" result="blurred" />
          <feColorMatrix in="blurred" type="matrix"
            values={eyeColorMatrix(palette.eyes)}
            result="tinted" />
          <feBlend in="SourceGraphic" in2="tinted" mode="screen" />
        </filter>

        {/* Specular highlight for metallic accessories */}
        <filter id={`spec-${id}`} x="-5%" y="-5%" width="110%" height="110%">
          <feSpecularLighting surfaceScale="4" specularConstant="1.2" specularExponent="30" lightingColor="white" result="specOut">
            <fePointLight x="60" y="30" z="150" />
          </feSpecularLighting>
          <feComposite in="specOut" in2="SourceGraphic" operator="in" />
        </filter>
      </defs>

      {/* ── Ground shadow ── */}
      <ellipse cx="140" cy="254" rx={bodyW + 12} ry="7" fill="rgba(0,0,0,0.5)" />

      {/* ── Tail ── */}
      {!isCritical && <AnimatedTail bodyW={bodyW} silhouette={silhouette} palette={palette} />}

      {/* ── Haunches (hip depth) ── */}
      <ellipse cx={140 + bodyW * 0.7} cy={200} rx={bodyW * 0.38} ry={bodyH * 0.55}
        fill={darken(palette.body, 0.15)} />
      <ellipse cx={140 - bodyW * 0.7} cy={202} rx={bodyW * 0.32} ry={bodyH * 0.48}
        fill={darken(palette.body, 0.18)} />

      {/* ── Body ── */}
      <ellipse cx="140" cy="196" rx={bodyW} ry={bodyH} fill={`url(#body-${id})`}
        filter={`url(#fur-${id})`} />
      {/* Rim light overlay on body */}
      <ellipse cx="140" cy="196" rx={bodyW} ry={bodyH} fill={palette.body}
        filter={`url(#rim-${id})`} />

      {/* Pattern overlay */}
      {(silhouette.pattern === 'stripes' || silhouette.pattern === 'spots') && (
        <ellipse cx="140" cy="196" rx={bodyW} ry={bodyH} fill={`url(#pat-${id})`} />
      )}

      {/* ── Belly ── */}
      <ellipse cx="140" cy="216" rx={bodyW * 0.58} ry={bodyH * 0.52}
        fill={`url(#belly-${id})`} opacity="0.92" />

      {/* Tuxedo chest patch */}
      {silhouette.pattern === 'tuxedo' && (
        <ellipse cx="140" cy="200" rx={bodyW * 0.4} ry={bodyH * 0.72} fill="#fafafa" opacity="0.95" />
      )}

      {/* Calico patches */}
      {silhouette.pattern === 'patches' && (
        <>
          <ellipse cx="112" cy="182" rx="19" ry="14" fill={palette.accent} opacity="0.82" />
          <ellipse cx="158" cy="202" rx="15" ry="12" fill="#2a1508" opacity="0.65" />
          <ellipse cx="140" cy="215" rx="12" ry="9" fill={palette.accent} opacity="0.55" />
        </>
      )}

      {/* ── Chest furrow (depth line) ── */}
      <path d={`M 140 ${196 - bodyH * 0.3} Q 140 ${196 + bodyH * 0.1} 140 ${196 + bodyH * 0.5}`}
        stroke={darken(palette.body, 0.2)} strokeWidth="1.5" fill="none" opacity="0.4" />

      {/* ── Neck ── */}
      <ellipse cx="140" cy="165" rx="24" ry="16"
        fill={`url(#body-${id})`} filter={`url(#fur-${id})`} />

      {/* ── Front paws ── */}
      <Paws palette={palette} />

      {/* ── Head group ── */}
      <g>
        {/* Ear group — left ear on separate twitch timer */}
        <motion.g
          animate={{ rotate: [0, 0, 0, -4, 1.5, 0, 0, 0, 0, 0] }}
          transition={{ duration: 6.5, repeat: Infinity, times: [0, 0.35, 0.44, 0.47, 0.5, 0.54, 0.65, 0.8, 0.9, 1], ease: 'easeOut' }}
          style={{ transformOrigin: '108px 106px' }}
        >
          <EarLeft shape={silhouette.ear} palette={palette} pinkId={`pink-${id}`} earTilt={earTilt} furId={`fur-${id}`} sssId={`sss-${id}`} />
        </motion.g>
        {/* Right ear on slightly different timer */}
        <motion.g
          animate={{ rotate: [0, 0, 0, 0, 3, -1, 0, 0] }}
          transition={{ duration: 8.2, repeat: Infinity, times: [0, 0.45, 0.5, 0.56, 0.59, 0.63, 0.68, 1], ease: 'easeOut' }}
          style={{ transformOrigin: '172px 106px' }}
        >
          <EarRight shape={silhouette.ear} palette={palette} pinkId={`pink-${id}`} earTilt={earTilt} furId={`fur-${id}`} sssId={`sss-${id}`} />
        </motion.g>

        {/* Long-fur cheek fluff */}
        {silhouette.fur === 'long' && (
          <>
            <ellipse cx="76" cy="140" rx="15" ry="22" fill={palette.body} filter={`url(#fur-${id})`} />
            <ellipse cx="204" cy="140" rx="15" ry="22" fill={palette.body} filter={`url(#fur-${id})`} />
          </>
        )}

        {/* Head skull */}
        <ellipse cx="140" cy="118" rx="58" ry="50" fill={`url(#head-${id})`}
          filter={`url(#fur-${id})`} />

        {/* Rim light on head */}
        <ellipse cx="140" cy="118" rx="58" ry="50" fill={palette.body}
          filter={`url(#rim-${id})`} />

        {/* Colorpoint mask */}
        {silhouette.pattern === 'colorpoint' && (
          <ellipse cx="140" cy="134" rx="42" ry="30" fill={palette.accent} opacity="0.52" />
        )}

        {/* Forehead highlights (soft fur shine) */}
        <ellipse cx="118" cy="94" rx="18" ry="9" fill={lighten(palette.body, 0.5)} opacity="0.3" />
        <ellipse cx="162" cy="94" rx="18" ry="9" fill={lighten(palette.body, 0.5)} opacity="0.3" />

        {/* Nose bridge highlight */}
        <ellipse cx="140" cy="116" rx="10" ry="24" fill={lighten(palette.body, 0.22)} opacity="0.3" />

        {/* Brow ridges (subtle expression depth) */}
        <path d={`M ${108 - 14} ${132 - 28} Q ${108} ${132 - 34} ${108 + 14} ${132 - 28}`}
          stroke={darken(palette.body, 0.28)} strokeWidth="1.8" fill="none" opacity="0.5" />
        <path d={`M ${172 - 14} ${132 - 28} Q ${172} ${132 - 34} ${172 + 14} ${132 - 28}`}
          stroke={darken(palette.body, 0.28)} strokeWidth="1.8" fill="none" opacity="0.5" />

        {/* Eyes */}
        <Eyes id={id} eyeOpen={eyeOpen} mood={mood} palette={palette} />

        {/* Muzzle protrusion */}
        <ellipse cx="140" cy="152" rx="20" ry="12" fill={lighten(palette.belly, 0.08)} opacity="0.75" />

        {/* Nose */}
        <path
          d="M 132 148 Q 140 160 148 148 Q 145 155 140 155 Q 135 155 132 148 Z"
          fill={`url(#nose-${id})`}
        />
        <ellipse cx="138" cy="150" rx="2.2" ry="1.4" fill="#ffffff" opacity="0.6" />

        {/* Chin pad */}
        <ellipse cx="140" cy="166" rx="14" ry="8" fill={lighten(palette.belly, 0.12)} opacity="0.65" />

        {/* Mouth */}
        <Mouth mood={mood} />

        {/* Whiskers */}
        <Whiskers palette={palette} />
      </g>

      {/* ── Glowing mood sparkle stars ── */}
      {isGlowing && <GlowStars palette={palette} />}

      {/* ── Accessories ── */}
      {equipped.map((key) => {
        const acc = getAccessory(key);
        if (!acc) return null;
        if (acc.render && accImages[key]) {
          const { cx, cy, w, h, rotation } = acc.render;
          return (
            <image
              key={key}
              href={`/companion/accessories/${key}.png`}
              x={cx - w / 2} y={cy - h / 2}
              width={w} height={h}
              style={{ transformOrigin: `${cx}px ${cy}px`, transform: `rotate(${rotation}deg)` }}
            />
          );
        }
        return <AccessorySvg key={key} acc={acc} id={id} specId={`spec-${id}`} />;
      })}

      {/* ── Sleeping zzz ── */}
      {mood === 'critical' && (
        <motion.text
          x="200" y="80"
          fontSize="24"
          fill="var(--text-secondary)"
          fontFamily="monospace"
          animate={{ opacity: [0.25, 1, 0.25], y: [80, 62, 80] }}
          transition={{ duration: 2.8, repeat: Infinity, ease: 'easeInOut' }}
        >
          z
        </motion.text>
      )}

      {/* ── Glow mood filter overlay ── */}
      {isGlowing && (
        <ellipse cx="140" cy="165" rx="100" ry="110" fill={palette.eyes}
          opacity="0.06" filter={`url(#glow-${id})`} />
      )}
    </svg>
  );
}

// ─── Animated tail ────────────────────────────────────────────────────────

function AnimatedTail({ bodyW, silhouette, palette }) {
  const strokeW = silhouette.fur === 'long' ? 26 : silhouette.fur === 'medium' ? 22 : 18;
  const tip = silhouette.tail === 'long' ? 58 : 88;
  const ctrl = silhouette.tail === 'long' ? 110 : 130;

  return (
    <motion.path
      stroke={palette.body}
      strokeWidth={strokeW}
      strokeLinecap="round"
      fill="none"
      animate={{
        d: [
          `M ${140 + bodyW * 0.58} 200 Q ${140 + bodyW * 1.25} ${ctrl} ${140 + bodyW} ${tip}`,
          `M ${140 + bodyW * 0.58} 200 Q ${140 + bodyW * 0.8} ${ctrl - 20} ${140 + bodyW * 0.95} ${tip + 20}`,
          `M ${140 + bodyW * 0.58} 200 Q ${140 + bodyW * 1.35} ${ctrl + 10} ${140 + bodyW * 1.05} ${tip - 10}`,
          `M ${140 + bodyW * 0.58} 200 Q ${140 + bodyW * 1.25} ${ctrl} ${140 + bodyW} ${tip}`,
        ],
      }}
      transition={{ duration: 5.5, repeat: Infinity, ease: 'easeInOut', times: [0, 0.35, 0.7, 1] }}
    />
  );
}

// ─── Ear components ───────────────────────────────────────────────────────

function EarLeft({ shape, palette, pinkId, earTilt, furId, sssId }) {
  const tilt = earTilt - 3;
  if (shape === 'folded') {
    return (
      <g transform={`rotate(${tilt}, 108, 114)`}>
        <ellipse cx="108" cy="102" rx="20" ry="10" fill={palette.body} filter={`url(#${furId})`} />
        <ellipse cx="108" cy="104" rx="13" ry="6" fill={`url(#${pinkId})`} filter={`url(#${sssId})`} />
      </g>
    );
  }
  if (shape === 'tufted') {
    return (
      <g transform={`rotate(${tilt}, 108, 114)`}>
        <polygon points="86,114 94,68 130,106" fill={palette.body} filter={`url(#${furId})`} />
        <polygon points="92,112 100,74 124,106" fill={`url(#${pinkId})`} opacity="0.7" filter={`url(#${sssId})`} />
        {/* Tuft */}
        <line x1="90" y1="70" x2="84" y2="54" stroke={palette.body} strokeWidth="3" strokeLinecap="round" />
        <line x1="95" y1="66" x2="92" y2="50" stroke={palette.body} strokeWidth="2.5" strokeLinecap="round" />
        <line x1="100" y1="66" x2="100" y2="50" stroke={palette.body} strokeWidth="2" strokeLinecap="round" />
      </g>
    );
  }
  // pointed (default)
  return (
    <g transform={`rotate(${tilt}, 108, 114)`}>
      <polygon points="86,116 96,68 132,108" fill={palette.body} filter={`url(#${furId})`} />
      <polygon points="92,114 100,76 126,108" fill={`url(#${pinkId})`} opacity="0.72" filter={`url(#${sssId})`} />
    </g>
  );
}

function EarRight({ shape, palette, pinkId, earTilt, furId, sssId }) {
  const tilt = -(earTilt - 3);
  if (shape === 'folded') {
    return (
      <g transform={`rotate(${tilt}, 172, 114)`}>
        <ellipse cx="172" cy="102" rx="20" ry="10" fill={palette.body} filter={`url(#${furId})`} />
        <ellipse cx="172" cy="104" rx="13" ry="6" fill={`url(#${pinkId})`} filter={`url(#${sssId})`} />
      </g>
    );
  }
  if (shape === 'tufted') {
    return (
      <g transform={`rotate(${tilt}, 172, 114)`}>
        <polygon points="194,114 186,68 150,106" fill={palette.body} filter={`url(#${furId})`} />
        <polygon points="188,112 180,74 156,106" fill={`url(#${pinkId})`} opacity="0.7" filter={`url(#${sssId})`} />
        <line x1="190" y1="70" x2="196" y2="54" stroke={palette.body} strokeWidth="3" strokeLinecap="round" />
        <line x1="185" y1="66" x2="188" y2="50" stroke={palette.body} strokeWidth="2.5" strokeLinecap="round" />
        <line x1="180" y1="66" x2="180" y2="50" stroke={palette.body} strokeWidth="2" strokeLinecap="round" />
      </g>
    );
  }
  return (
    <g transform={`rotate(${tilt}, 172, 114)`}>
      <polygon points="194,116 184,68 148,108" fill={palette.body} filter={`url(#${furId})`} />
      <polygon points="188,114 180,76 154,108" fill={`url(#${pinkId})`} opacity="0.72" filter={`url(#${sssId})`} />
    </g>
  );
}

// ─── Eyes ─────────────────────────────────────────────────────────────────

function Eyes({ id, eyeOpen, mood, palette }) {
  const pupilMood = mood === 'distressed' ? 0.62 : mood === 'glowing' ? 0.22 : 0.34;

  return (
    <motion.g
      animate={{ scaleY: [1, 1, 1, 0.07, 1, 1] }}
      transition={{
        duration: 4.8,
        repeat: Infinity,
        times: [0, 0.82, 0.92, 0.94, 0.97, 1],
        ease: 'linear',
      }}
      style={{ transformOrigin: '140px 132px' }}
    >
      <SingleEye cx={108} cy={132} rx={16} ry={21 * eyeOpen} id={id} mood={mood} palette={palette} pupilW={pupilMood} />
      <SingleEye cx={172} cy={132} rx={16} ry={21 * eyeOpen} id={id} mood={mood} palette={palette} pupilW={pupilMood} />
    </motion.g>
  );
}

function SingleEye({ cx, cy, rx, ry, id, mood, palette, pupilW }) {
  if (ry < 1.5) {
    return (
      <path
        d={`M ${cx - rx} ${cy} Q ${cx} ${cy + 5} ${cx + rx} ${cy}`}
        stroke="#0a0a0a"
        strokeWidth="2.8"
        fill="none"
        strokeLinecap="round"
      />
    );
  }
  const pupilOffset = (mood === 'concerned' || mood === 'distressed') ? -2 : 0;
  return (
    <g>
      {/* White sclera */}
      <ellipse cx={cx} cy={cy} rx={rx + 1} ry={ry + 1} fill="#fafafa" />
      {/* Iris gradient */}
      <ellipse cx={cx} cy={cy + 1} rx={rx} ry={ry} fill={`url(#eye-${id})`} />
      {/* Limbal ring */}
      <ellipse cx={cx} cy={cy} rx={rx} ry={ry} fill="none"
        stroke={darken(palette.eyes, 0.6)} strokeWidth="2" opacity="0.7" />
      {/* Iris detail rings */}
      <ellipse cx={cx} cy={cy + 1} rx={rx * 0.75} ry={ry * 0.75} fill="none"
        stroke={darken(palette.eyes, 0.25)} strokeWidth="0.8" opacity="0.35" />
      <ellipse cx={cx} cy={cy + 1} rx={rx * 0.5} ry={ry * 0.5} fill="none"
        stroke={lighten(palette.eyes, 0.2)} strokeWidth="0.6" opacity="0.3" />
      {/* Vertical feline pupil */}
      <ellipse cx={cx + pupilOffset} cy={cy + 2} rx={rx * pupilW} ry={ry * 0.82} fill="#050505" />
      {/* Corneal dome highlight (large upper arc) */}
      <ellipse cx={cx - rx * 0.18} cy={cy - ry * 0.28} rx={rx * 0.68} ry={ry * 0.32}
        fill="#ffffff" opacity="0.92" />
      {/* Secondary small catchlight */}
      <circle cx={cx + rx * 0.42} cy={cy + ry * 0.3} r={rx * 0.15} fill="#ffffff" opacity="0.7" />
      {/* Eyelid upper fold */}
      <path d={`M ${cx - rx} ${cy - ry * 0.2} Q ${cx} ${cy - ry * 1.1} ${cx + rx} ${cy - ry * 0.2}`}
        stroke="#0a0a0a" strokeWidth="1.8" fill="none" />
    </g>
  );
}

// ─── Paws ─────────────────────────────────────────────────────────────────

function Paws({ palette }) {
  return (
    <g>
      {/* Left paw */}
      <motion.g
        animate={{ y: [0, 0, -5, 0, 0, 0], scaleY: [1, 1, 0.85, 1, 1, 1] }}
        transition={{ duration: 9, repeat: Infinity, times: [0, 0.35, 0.4, 0.45, 0.55, 1], ease: 'easeInOut' }}
        style={{ transformOrigin: '118px 242px' }}
      >
        <ellipse cx="118" cy="242" rx="15" ry="9" fill={palette.body} />
        <ellipse cx="116" cy="243" rx="6.5" ry="3" fill={lighten(palette.belly, 0.12)} opacity="0.75" />
        {/* Toe beans */}
        <circle cx="110" cy="246" r="2.5" fill={darken(palette.belly, 0.1)} opacity="0.6" />
        <circle cx="116" cy="248" r="2.5" fill={darken(palette.belly, 0.1)} opacity="0.6" />
        <circle cx="122" cy="246" r="2.5" fill={darken(palette.belly, 0.1)} opacity="0.6" />
      </motion.g>
      {/* Right paw */}
      <ellipse cx="162" cy="242" rx="15" ry="9" fill={palette.body} />
      <ellipse cx="164" cy="243" rx="6.5" ry="3" fill={lighten(palette.belly, 0.12)} opacity="0.75" />
      <circle cx="156" cy="246" r="2.5" fill={darken(palette.belly, 0.1)} opacity="0.6" />
      <circle cx="162" cy="248" r="2.5" fill={darken(palette.belly, 0.1)} opacity="0.6" />
      <circle cx="168" cy="246" r="2.5" fill={darken(palette.belly, 0.1)} opacity="0.6" />
    </g>
  );
}

// ─── Mouth & Whiskers ────────────────────────────────────────────────────

function Mouth({ mood }) {
  if (mood === 'critical' || mood === 'distressed') {
    return <path d="M 127 163 Q 140 157 153 163" stroke="#1a1a1a" strokeWidth="2.4" fill="none" strokeLinecap="round" />;
  }
  if (mood === 'concerned') {
    return <path d="M 130 163 L 150 163" stroke="#1a1a1a" strokeWidth="2.4" fill="none" strokeLinecap="round" />;
  }
  return (
    <g>
      <path d="M 129 161 Q 135 167 140 163" stroke="#1a1a1a" strokeWidth="2.2" fill="none" strokeLinecap="round" />
      <path d="M 140 163 Q 145 167 151 161" stroke="#1a1a1a" strokeWidth="2.2" fill="none" strokeLinecap="round" />
    </g>
  );
}

function Whiskers({ palette }) {
  const wColor = darken(palette.body, 0.05);
  return (
    <motion.g
      animate={{ rotate: [0, 0, -1.5, 0, 1.5, 0, 0] }}
      transition={{ duration: 5, repeat: Infinity, times: [0, 0.4, 0.45, 0.5, 0.55, 0.6, 1] }}
      style={{ transformOrigin: '140px 152px' }}
    >
      {/* Left whiskers */}
      <line x1="22" y1="146" x2="122" y2="151" stroke={wColor} strokeWidth="0.9" opacity="0.4" />
      <line x1="20" y1="152" x2="122" y2="153" stroke={wColor} strokeWidth="0.9" opacity="0.4" />
      <line x1="24" y1="158" x2="122" y2="156" stroke={wColor} strokeWidth="0.8" opacity="0.35" />
      {/* Right whiskers */}
      <line x1="258" y1="146" x2="158" y2="151" stroke={wColor} strokeWidth="0.9" opacity="0.4" />
      <line x1="260" y1="152" x2="158" y2="153" stroke={wColor} strokeWidth="0.9" opacity="0.4" />
      <line x1="256" y1="158" x2="158" y2="156" stroke={wColor} strokeWidth="0.8" opacity="0.35" />
    </motion.g>
  );
}

// ─── Glowing mood sparkle stars ───────────────────────────────────────────

function GlowStars({ palette }) {
  const stars = [
    { r: 75, offset: 0,       size: 7  },
    { r: 82, offset: 0.25,    size: 5  },
    { r: 70, offset: 0.5,     size: 6  },
    { r: 80, offset: 0.75,    size: 4  },
  ];
  return (
    <motion.g
      animate={{ rotate: 360 }}
      transition={{ duration: 8, repeat: Infinity, ease: 'linear' }}
      style={{ transformOrigin: '140px 118px' }}
    >
      {stars.map((s, i) => {
        const angle = s.offset * Math.PI * 2;
        const x = 140 + Math.cos(angle) * s.r;
        const y = 118 + Math.sin(angle) * s.r;
        return (
          <motion.polygon
            key={i}
            points={starPoints(x, y, s.size, s.size * 0.4)}
            fill={palette.eyes}
            animate={{ opacity: [0.5, 1, 0.5] }}
            transition={{ duration: 1.6, repeat: Infinity, delay: i * 0.4, ease: 'easeInOut' }}
          />
        );
      })}
    </motion.g>
  );
}

function starPoints(cx, cy, r, ir, n = 5) {
  let pts = '';
  for (let i = 0; i < n * 2; i++) {
    const angle = (i * Math.PI) / n - Math.PI / 2;
    const rad = i % 2 === 0 ? r : ir;
    pts += `${(cx + Math.cos(angle) * rad).toFixed(2)},${(cy + Math.sin(angle) * rad).toFixed(2)} `;
  }
  return pts.trim();
}

// ─── Accessory SVG fallback renderer ─────────────────────────────────────

function AccessorySvg({ acc, id, specId }) {
  const { key, slot, color, render } = acc;
  if (!render) return null;
  const { cx, cy, w, h, rotation } = render;

  const tint = color;
  const hi = lighten(color, 0.55);
  const sha = darken(color, 0.45);

  return (
    <g transform={`rotate(${rotation}, ${cx}, ${cy})`}>
      {slot === 'neck' && <NeckAccessory acc={acc} cx={cx} cy={cy} w={w} h={h} tint={tint} hi={hi} sha={sha} id={id} specId={specId} />}
      {slot === 'head' && <HeadAccessory acc={acc} cx={cx} cy={cy} w={w} h={h} tint={tint} hi={hi} sha={sha} id={id} specId={specId} />}
      {slot === 'back' && <BackAccessory acc={acc} cx={cx} cy={cy} w={w} h={h} tint={tint} hi={hi} sha={sha} />}
      {slot === 'shoulder' && <ShoulderAccessory acc={acc} cx={cx} cy={cy} w={w} h={h} tint={tint} hi={hi} sha={sha} />}
    </g>
  );
}

function NeckAccessory({ acc, cx, cy, w, h, tint, hi, sha }) {
  const isCollar = acc.key !== 'ebony_cravat' && acc.key !== 'silverbell';
  if (acc.key === 'ebony_cravat') {
    return (
      <g>
        <ellipse cx={cx} cy={cy - h * 0.1} rx={w * 0.5} ry={h * 0.22}
          fill={tint} stroke={sha} strokeWidth="1" />
        <polygon points={`${cx - w * 0.18},${cy + h * 0.1} ${cx + w * 0.18},${cy + h * 0.1} ${cx},${cy + h * 0.45}`}
          fill={tint} />
        <ellipse cx={cx - w * 0.04} cy={cy + h * 0.08} rx={w * 0.06} ry={w * 0.06}
          fill={hi} opacity="0.7" />
        <ellipse cx={cx} cy={cy - h * 0.1} rx={w * 0.5} ry={h * 0.22}
          fill={hi} opacity="0.15" />
      </g>
    );
  }
  if (acc.key === 'silverbell') {
    return (
      <g>
        <path d={`M ${cx - w * 0.5} ${cy} Q ${cx} ${cy - h * 0.5} ${cx + w * 0.5} ${cy}`}
          stroke={tint} strokeWidth="3" fill="none" />
        <ellipse cx={cx} cy={cy + h * 0.1} rx={w * 0.22} ry={h * 0.38}
          fill={tint} stroke={sha} strokeWidth="1" />
        <ellipse cx={cx - w * 0.06} cy={cy - h * 0.08} rx={w * 0.1} ry={h * 0.1}
          fill={hi} opacity="0.65" />
        <line x1={cx} y1={cy + h * 0.44} x2={cx} y2={cy + h * 0.54}
          stroke={sha} strokeWidth="1.5" />
      </g>
    );
  }
  // Standard collar
  return (
    <g>
      <rect x={cx - w * 0.5} y={cy - h * 0.5} width={w} height={h}
        rx={h * 0.45}
        fill={tint}
        stroke={sha}
        strokeWidth="1.2"
      />
      {/* Highlight band */}
      <rect x={cx - w * 0.5} y={cy - h * 0.5} width={w} height={h * 0.45}
        rx={h * 0.35}
        fill={hi}
        opacity="0.22"
      />
      {/* Gemstone centre */}
      <ellipse cx={cx} cy={cy} rx={h * 0.55} ry={h * 0.55}
        fill={hi}
        stroke={sha}
        strokeWidth="0.8"
      />
      <ellipse cx={cx - h * 0.15} cy={cy - h * 0.2} rx={h * 0.2} ry={h * 0.15}
        fill="#ffffff"
        opacity="0.7"
      />
    </g>
  );
}

function HeadAccessory({ acc, cx, cy, w, h, tint, hi, sha }) {
  if (acc.key === 'halo_of_the_first_sun') {
    return (
      <motion.g
        animate={{ y: [0, -2, 0], opacity: [0.85, 1, 0.85] }}
        transition={{ duration: 2.2, repeat: Infinity, ease: 'easeInOut' }}
      >
        <ellipse cx={cx} cy={cy} rx={w * 0.48} ry={h * 0.42}
          fill="none" stroke={tint} strokeWidth="5" />
        <ellipse cx={cx} cy={cy} rx={w * 0.48} ry={h * 0.42}
          fill="none" stroke={hi} strokeWidth="2.5" opacity="0.6" />
        {/* Rune marks */}
        {[0, 72, 144, 216, 288].map((deg, i) => {
          const rad = (deg * Math.PI) / 180;
          const rx2 = w * 0.48, ry2 = h * 0.42;
          const px = cx + Math.cos(rad) * rx2;
          const py = cy + Math.sin(rad) * ry2;
          return <circle key={i} cx={px} cy={py} r="2.5" fill={tint} opacity="0.8" />;
        })}
      </motion.g>
    );
  }
  if (acc.key === 'arcanist_cap') {
    return (
      <g>
        <path d={`M ${cx - w * 0.5} ${cy + h * 0.5} L ${cx} ${cy - h * 0.5} L ${cx + w * 0.5} ${cy + h * 0.5} Z`}
          fill={tint} stroke={sha} strokeWidth="1.5" />
        <path d={`M ${cx - w * 0.5} ${cy + h * 0.5} L ${cx} ${cy - h * 0.5} L ${cx + w * 0.5} ${cy + h * 0.5} Z`}
          fill={hi} opacity="0.12" />
        <ellipse cx={cx} cy={cy + h * 0.5} rx={w * 0.55} ry={h * 0.15}
          fill={tint} stroke={sha} strokeWidth="1" />
        {/* Moon */}
        <path d={`M ${cx - 6} ${cy - 5} Q ${cx + 4} ${cy - 12} ${cx + 8} ${cy - 4} Q ${cx + 2} ${cy - 2} ${cx - 6} ${cy - 5} Z`}
          fill={hi} opacity="0.75" />
      </g>
    );
  }
  if (acc.key === 'crown_of_embers') {
    const pts = 9;
    const baseY = cy + h * 0.4;
    const baseX1 = cx - w * 0.45;
    return (
      <g>
        {/* Crown band */}
        <path d={`M ${baseX1} ${baseY} Q ${cx} ${baseY + 6} ${cx + w * 0.45} ${baseY}`}
          fill={tint} stroke={sha} strokeWidth="1.5" />
        {/* Spires */}
        {Array.from({ length: 5 }, (_, i) => {
          const t = i / 4;
          const px = baseX1 + t * w * 0.9;
          const ph = h * (0.3 + Math.sin(t * Math.PI) * 0.4);
          return (
            <g key={i}>
              <path d={`M ${px - 5} ${baseY} L ${px} ${baseY - ph} L ${px + 5} ${baseY}`}
                fill={tint} stroke={sha} strokeWidth="0.8" />
              <circle cx={px} cy={baseY - ph} r="3.5"
                fill={i === 2 ? hi : darken(tint, 0.2)} opacity="0.9" />
            </g>
          );
        })}
        {/* Band highlight */}
        <path d={`M ${baseX1} ${baseY} Q ${cx} ${baseY + 6} ${cx + w * 0.45} ${baseY}`}
          fill={hi} opacity="0.2" strokeWidth="0" />
      </g>
    );
  }
  if (acc.key === 'ironwolf_helm') {
    return (
      <g>
        <ellipse cx={cx} cy={cy} rx={w * 0.47} ry={h * 0.48}
          fill={tint} stroke={sha} strokeWidth="2" />
        <ellipse cx={cx} cy={cy} rx={w * 0.47} ry={h * 0.48}
          fill={hi} opacity="0.1" />
        {/* Visor slit */}
        <rect x={cx - w * 0.3} y={cy - h * 0.04} width={w * 0.6} height={h * 0.1}
          rx={3} fill={sha} opacity="0.8" />
        {/* Nose guard */}
        <rect x={cx - 4} y={cy - h * 0.04} width={8} height={h * 0.32}
          rx={2} fill={sha} opacity="0.7" />
        {/* Wolf ear nubs */}
        <polygon points={`${cx - w * 0.38},${cy - h * 0.38} ${cx - w * 0.26},${cy - h * 0.52} ${cx - w * 0.18},${cy - h * 0.36}`}
          fill={tint} stroke={sha} strokeWidth="1" />
        <polygon points={`${cx + w * 0.38},${cy - h * 0.38} ${cx + w * 0.26},${cy - h * 0.52} ${cx + w * 0.18},${cy - h * 0.36}`}
          fill={tint} stroke={sha} strokeWidth="1" />
        {/* Highlight */}
        <ellipse cx={cx - w * 0.12} cy={cy - h * 0.2} rx={w * 0.1} ry={h * 0.12}
          fill={hi} opacity="0.4" />
      </g>
    );
  }
  return (
    <g>
      <ellipse cx={cx} cy={cy} rx={w * 0.48} ry={h * 0.48}
        fill={tint} stroke={sha} strokeWidth="1.5" />
      <ellipse cx={cx - w * 0.1} cy={cy - h * 0.15} rx={w * 0.2} ry={h * 0.18}
        fill={hi} opacity="0.5" />
    </g>
  );
}

function BackAccessory({ acc, cx, cy, w, h, tint, hi, sha }) {
  const isWings = acc.key === 'gilded_wings' || acc.key === 'dragon_wings';
  const isDragon = acc.key === 'dragon_wings';

  if (isWings) {
    return (
      <motion.g
        animate={{ scaleY: [1, 1.05, 1], rotate: [0, 1.5, -1, 0] }}
        transition={{ duration: 3.5, repeat: Infinity, ease: 'easeInOut' }}
        style={{ transformOrigin: `${cx}px ${cy}px` }}
      >
        {/* Left wing */}
        <path
          d={`M ${cx - 10} ${cy - 10}
             Q ${cx - w * 0.35} ${cy - h * 0.55}
               ${cx - w * 0.5} ${cy - h * 0.1}
             Q ${cx - w * 0.45} ${cy + h * 0.32}
               ${cx - 15} ${cy + h * 0.22} Z`}
          fill={tint} stroke={sha} strokeWidth="1.5" opacity="0.92"
        />
        {/* Right wing */}
        <path
          d={`M ${cx + 10} ${cy - 10}
             Q ${cx + w * 0.35} ${cy - h * 0.55}
               ${cx + w * 0.5} ${cy - h * 0.1}
             Q ${cx + w * 0.45} ${cy + h * 0.32}
               ${cx + 15} ${cy + h * 0.22} Z`}
          fill={tint} stroke={sha} strokeWidth="1.5" opacity="0.92"
        />
        {/* Wing highlights */}
        <path
          d={`M ${cx - 10} ${cy - 10} Q ${cx - w * 0.3} ${cy - h * 0.45} ${cx - w * 0.44} ${cy - h * 0.06}`}
          stroke={isDragon ? '#8a2020' : hi} strokeWidth="2.5" fill="none" opacity="0.55"
        />
        <path
          d={`M ${cx + 10} ${cy - 10} Q ${cx + w * 0.3} ${cy - h * 0.45} ${cx + w * 0.44} ${cy - h * 0.06}`}
          stroke={isDragon ? '#8a2020' : hi} strokeWidth="2.5" fill="none" opacity="0.55"
        />
        {/* Membrane veins (dragon) */}
        {isDragon && (
          <>
            <path d={`M ${cx - 10} ${cy - 8} Q ${cx - w * 0.2} ${cy + h * 0.05} ${cx - w * 0.38} ${cy + h * 0.28}`}
              stroke="#6a0f0f" strokeWidth="1.5" fill="none" opacity="0.5" />
            <path d={`M ${cx + 10} ${cy - 8} Q ${cx + w * 0.2} ${cy + h * 0.05} ${cx + w * 0.38} ${cy + h * 0.28}`}
              stroke="#6a0f0f" strokeWidth="1.5" fill="none" opacity="0.5" />
          </>
        )}
        {/* Gold sheen (gilded) */}
        {!isDragon && (
          <>
            <path d={`M ${cx - 16} ${cy - 12} Q ${cx - w * 0.28} ${cy - h * 0.42} ${cx - w * 0.42} ${cy - h * 0.04}`}
              stroke={hi} strokeWidth="4" fill="none" opacity="0.25" />
            <path d={`M ${cx + 16} ${cy - 12} Q ${cx + w * 0.28} ${cy - h * 0.42} ${cx + w * 0.42} ${cy - h * 0.04}`}
              stroke={hi} strokeWidth="4" fill="none" opacity="0.25" />
          </>
        )}
      </motion.g>
    );
  }

  // Crimson mantle (cape)
  return (
    <g>
      <path d={`M ${cx - w * 0.5} ${cy - h * 0.45} Q ${cx} ${cy - h * 0.3} ${cx + w * 0.5} ${cy - h * 0.45}
                L ${cx + w * 0.45} ${cy + h * 0.48} Q ${cx} ${cy + h * 0.55} ${cx - w * 0.45} ${cy + h * 0.48} Z`}
        fill={tint} stroke={sha} strokeWidth="1.5" />
      {/* Fur trim */}
      <path d={`M ${cx - w * 0.5} ${cy - h * 0.45} Q ${cx} ${cy - h * 0.28} ${cx + w * 0.5} ${cy - h * 0.45}`}
        stroke="#d4c8b8" strokeWidth="5" fill="none" opacity="0.7" />
      {/* Highlight fold */}
      <path d={`M ${cx - w * 0.2} ${cy - h * 0.3} Q ${cx} ${cy + h * 0.1} ${cx + w * 0.2} ${cy - h * 0.25}`}
        stroke={hi} strokeWidth="2" fill="none" opacity="0.35" />
    </g>
  );
}

function ShoulderAccessory({ acc, cx, cy, w, h, tint, hi, sha }) {
  // Raven's pauldron
  return (
    <g>
      <ellipse cx={cx} cy={cy + h * 0.05} rx={w * 0.46} ry={h * 0.42}
        fill={tint} stroke={sha} strokeWidth="1.5" />
      {/* Plate ridges */}
      {[-1, 0, 1].map((i) => (
        <path key={i}
          d={`M ${cx - w * 0.35} ${cy + i * h * 0.12} Q ${cx} ${cy + i * h * 0.1 - 4} ${cx + w * 0.35} ${cy + i * h * 0.12}`}
          stroke={sha} strokeWidth="1.2" fill="none" opacity="0.5"
        />
      ))}
      {/* Raven silhouette */}
      <ellipse cx={cx + w * 0.05} cy={cy - h * 0.28} rx={w * 0.18} ry={h * 0.14}
        fill="#0a0a0a" />
      <polygon points={`${cx - w * 0.08},${cy - h * 0.32} ${cx + w * 0.08},${cy - h * 0.36} ${cx + w * 0.28},${cy - h * 0.26}`}
        fill="#0a0a0a" />
      {/* Highlight */}
      <ellipse cx={cx - w * 0.1} cy={cy - h * 0.08} rx={w * 0.14} ry={h * 0.12}
        fill={hi} opacity="0.35" />
    </g>
  );
}

// ─── Colour helpers ────────────────────────────────────────────────────────

function hexToRgb(hex) {
  const h = hex.replace('#', '');
  if (h.length === 3) {
    return [
      parseInt(h[0] + h[0], 16),
      parseInt(h[1] + h[1], 16),
      parseInt(h[2] + h[2], 16),
    ];
  }
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ];
}

function rgbToHex(r, g, b) {
  return '#' + [r, g, b].map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('');
}

function lighten(hex, amount) {
  if (!hex?.startsWith('#')) return hex || '#888';
  const [r, g, b] = hexToRgb(hex);
  return rgbToHex(r + (255 - r) * amount, g + (255 - g) * amount, b + (255 - b) * amount);
}

function darken(hex, amount) {
  if (!hex?.startsWith('#')) return hex || '#333';
  const [r, g, b] = hexToRgb(hex);
  return rgbToHex(r * (1 - amount), g * (1 - amount), b * (1 - amount));
}

function eyeColorMatrix(hex) {
  if (!hex?.startsWith('#')) return '1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 0.5 0';
  const [r, g, b] = hexToRgb(hex);
  const nr = (r / 255 * 2.5).toFixed(2);
  const ng = (g / 255 * 2.5).toFixed(2);
  const nb = (b / 255 * 2.5).toFixed(2);
  return `${nr} 0 0 0 0  0 ${ng} 0 0 0  0 0 ${nb} 0 0  0 0 0 0.45 0`;
}
