import test from 'node:test';
import assert from 'node:assert/strict';
import { AnimationClip, Bone, BoxGeometry, Group, MeshBasicMaterial, NumberKeyframeTrack, Skeleton, SkinnedMesh } from 'three';
import { createChampionInstance } from '../champion-instance.mjs';

test('same-class champions animate independently and release only instance-owned resources', () => {
  const source = new Group();
  const bone = new Bone();
  bone.name = 'RootBone';
  const geometry = new BoxGeometry();
  const material = new MeshBasicMaterial();
  const mesh = new SkinnedMesh(geometry, material);
  mesh.add(bone);
  mesh.bind(new Skeleton([bone]));
  source.add(mesh);
  const clips = [new AnimationClip('walk', 1, [new NumberKeyframeTrack('RootBone.position[x]', [0, 1], [0, 1])])];
  const a = createChampionInstance(source, clips);
  const b = createChampionInstance(source, clips);
  const aMesh = a.root.children[0];
  const bMesh = b.root.children[0];
  assert.notEqual(aMesh.skeleton, bMesh.skeleton);
  assert.notEqual(aMesh.skeleton.bones[0], bMesh.skeleton.bones[0]);
  assert.equal(aMesh.geometry, bMesh.geometry);
  assert.equal(aMesh.material, bMesh.material);
  a.play('walk');
  b.play('walk');
  a.update(.1);
  b.update(.03);
  assert.ok(Math.abs(aMesh.skeleton.bones[0].position.x - .1) < .0001);
  assert.ok(Math.abs(bMesh.skeleton.bones[0].position.x - .03) < .0001);
  assert.equal(bone.position.x, 0);
  let geometryDisposals = 0;
  let materialDisposals = 0;
  geometry.addEventListener('dispose', () => geometryDisposals++);
  material.addEventListener('dispose', () => materialDisposals++);
  a.dispose();
  a.dispose();
  b.update(.1);
  assert.ok(bMesh.skeleton.bones[0].position.x > .12);
  assert.equal(geometryDisposals, 0);
  assert.equal(materialDisposals, 0);
  assert.throws(() => a.play('walk'), /disposed/);
  assert.throws(() => b.play('missing'), /Missing character clip/);
  b.dispose();
  geometry.dispose();
  material.dispose();
  mesh.skeleton.dispose();
});
